version: '1.0.{build}'
skip_non_tags: true 
image: Visual Studio 2017
branches:
  only:
  - master
configuration: Release
install:
  - cmd: dotnet restore
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build:
  verbosity: minimal
  project: NotifiqueMe.sln
build_script:
  - cmd: dotnet build
  - cmd: dotnet pack
  - cmd: cd NotifiqueMe.Tests
  - cmd: dotnet test
artifacts:
  - path: '**\NotifiqueMe*.nupkg'
    name: NotifiqueMeNuGet
#deploy:
  # NuGet
  #- provider: NuGet
  #  api_key:
  #    secure: ty/C9+zIqbXaj8BRG+aiDTMHgfdz9NMXjEVaOuQ/SjwHzhEjJpf+3QHKRwPTSceX # your encrypted token from Nuget
  #  skip_symbols: false
  #  artifact: NotifiqueMeNuGet
on_success:
  - echo Processo finalizado com sucesso!