version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
configuration: Release  
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build:
  project: NotifiqueMe.sln
  publish_nuget: true 
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore
build_script:
  - cmd: echo Iniciando build...
  - cmd: dotnet build
  - cmd: dotnet pack
test_script:
  - cmd: dotnet restore
  - cmd: cd NotifiqueMe.Tests
  - cmd: dotnet test
artifacts:
  - path: '**\*.nupkg'
  - path: NotifiqueMe.zip
    name: NotifiqueMeZip
    type: zip
deploy:
  release: NotifiqueMe-v$(appveyor_build_version)
  description: 'Release publicada pela integração com o AppVeyor' 
   # NuGet
  provider: NuGet
  api_key:
    secure: ty/C9+zIqbXaj8BRG+aiDTMHgfdz9NMXjEVaOuQ/SjwHzhEjJpf+3QHKRwPTSceX
  skip_symbols: false
  # GitHub
  provider: GitHub
  auth_token:
    secure: S8J30uBVO6nnJrL7MZ4EfUk0wX7mwlhLpXamPGijyaC6adefhnGAKuZzABknfkqb # your encrypted token from GitHub
  artifact: NotifiqueMeZip      
  draft: false
  prerelease: false
  on:
    branch: master                
    appveyor_repo_tag: true
on_finish :
  - echo Processo finalizado.