version: '3.0.0'
skip_non_tags: true 
image: Visual Studio 2017
branches:
  only:
  - master
configuration: Release
install:
  - cmd: dotnet restore
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(APPVEYOR_REPO_TAG_NAME)
  package_version: $(APPVEYOR_REPO_TAG_NAME)
  assembly_version: $(APPVEYOR_REPO_TAG_NAME)
  file_version: $(APPVEYOR_REPO_TAG_NAME)
  informational_version: $(APPVEYOR_REPO_TAG_NAME)
build:
  verbosity: minimal
  project: notifique-me.sln
build_script:
  - cmd: dotnet build
  - cmd: dotnet pack
  - cmd: cd notifique-me-tests
  - cmd: dotnet test
artifacts:
  - path: '**\NotifiqueMe*.nupkg'
    name: NotifiqueMeNuGet
deploy:
  # NuGet
  - provider: NuGet
    api_key:
      secure: 0/WZ9o7iCtXaw1wJXnF7UQfm8A1Kz3srLeCjgqL9lE9FvcB0Qtv9L33UG+E48dI0 # Encriptada em https://ci.appveyor.com/tools/encrypt
    skip_symbols: false
    artifact: NotifiqueMeNuGet
on_success:
  - echo Processo finalizado com sucesso!