version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
configuration: Release  
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build:
  project: NotifiqueMe.sln
  publish_nuget: true 
before_build:
  - cmd: echo Iniciando o processo...
  - cmd: dotnet --version
  - cmd: dotnet restore
build_script:
  - cmd: echo Iniciando build...
  - cmd: dotnet build
  - cmd: dotnet pack
test_script:
  - cmd: echo Iniciando testes...
  - cmd: dotnet restore
  - cmd: cd NotifiqueMe.Tests
  - cmd: dotnet test
artifacts:
  - path: '**\*.nupkg'
deploy: 
  provider: NuGet
  api_key:
    secure: ty/C9+zIqbXaj8BRG+aiDTMHgfdz9NMXjEVaOuQ/SjwHzhEjJpf+3QHKRwPTSceX
  skip_symbols: false
on_finish :
  - cmd: echo Processo finalizado.