version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
skip_tags: true
configuration: Release  
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore
build:
  project: NotifiqueMe.sln
  publish_nuget: true 
build_script:
  - cmd: dotnet build
  - cmd: dotnet pack
test_script:
  - cmd: dotnet restore
  - cmd: cd NotifiqueMe.Tests
  - cmd: dotnet test
artifacts:
  - path: '**\*.nupkg'
    name: NotifiqueMeNuGet
deploy:
   # NuGet
  - provider: NuGet
    api_key:
      secure: ty/C9+zIqbXaj8BRG+aiDTMHgfdz9NMXjEVaOuQ/SjwHzhEjJpf+3QHKRwPTSceX # your encrypted token from Nuget
    skip_symbols: false
    artifact: NotifiqueMeNuGet
 
  # GitHub
  - provider: GitHub
    tag: v$(appveyor_build_version)
    release: v$(appveyor_build_version)
    description: 'Release publicada pela integração com o AppVeyor'
    auth_token:
      secure: S8J30uBVO6nnJrL7MZ4EfUk0wX7mwlhLpXamPGijyaC6adefhnGAKuZzABknfkqb # your encrypted token from GitHub
    draft: false
    prerelease: false
    on:
      branch: master                
      appveyor_repo_tag: false
on_finish :
  - echo Processo finalizado.